[package]
name = "churchroad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egglog = { git = "https://github.com/egraphs-good/egglog", rev = "73a76dc9228ce24291b3e41bbbca14eddd10cd5e" }
egraph-serialize = "0.1.0"
log = "0.4.20"
