[package]
name = "churchroad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egglog = { path = "egglog" }
log = "0.4.20"
egraph-serialize = "0.1"
indexmap = "2.0.0"
