.PHONY: simulate

VERILATOR?=verilator

{simulation_executable_name}: {testbench_file_path}
	$(VERILATOR) -o {simulation_executable_name} -Wno-WIDTHTRUNC --assert --main --timing --Mdir {verilator_output_dir} --cc --exe --build $^ {extra_verilator_args}