// Tests functionality of `$shiftx`, which is what's generated by Yosys when it
// encounters something like `mem[idx]` in a design.
//
// RUN: $YOSYS -q -m $CHURCHROAD_DIR/yosys-plugin/churchroad.so \
// RUN:   -p 'read_verilog -sv %s; prep -top test; write_churchroad' 
//    | FileCheck %s

module test
(
    input  [63:0] mem,
    input  [5:0]  idx,
    output        O
);
    assign O = mem[idx];
endmodule

// CHECK: blah